### ISSUE TITLE
Noisy warning during precompilation: `AES-NI is not enabled, so AESNI and ARS are not available.`

### ISSUE THREAD

**Issue by IanButterworth** [sunoru/Random123.jl#18]
```
(@v1.11) pkg> precompile
Precompiling project...
  169 dependencies successfully precompiled in 104 seconds. 7 already precompiled.
  4 dependencies had output during precompilation:
┌ Random123
│  ┌ Warning: AES-NI is not enabled, so AESNI and ARS are not available.
│  └ @ Random123 ~/.julia/packages/Random123/u5oEp/src/Random123.jl:55
└  
```
```
julia> versioninfo()
Julia Version 1.11.0-DEV.507
Commit 06432bc1f7 (2023-09-19 11:26 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.5.0)
  CPU: 10 × Apple M2 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 6 virtual cores
```

**Comment by sunoru** [comment]
This warning only shows up during the precompiling. Is that too noisy? Usually users don't need to do that a lot.

I guess we can have an environment variable to mute the warning... What do you think?

**Comment by IanButterworth** [comment]
I don't directly depend on this package, and for me the warning isn't clear. I don't know what the acronyms are, what the implication is, or what to do about it.

If the warning needs to stay perhaps it could be more clear and helpful?

Otherwise it just seems a like noisy internal warning.

**Comment by sunoru** [comment]
I see. If it is not a direct dependency, the warning does look noisy and unclear... Thanks for pointing the problem out. BTW, `AESNI` and `ARS` are the names of two RNGs provided by this package, and because arm64 doesn't have AES-NI intrinsics, there is this warning.

I will make this warning more clear and maybe try to mute it if the package is indirectly used (is this possible?)

Actually a better solution is to support the two RNGs for arm64 since apple silicon is very popular now, and then there is no need for this warning at all. I will also look into that when I get time.

**Comment by pthariensflame** [comment]
@sunoru Would you like any help with the arm64 support?  I have such a machine and would love to contribute!

**Comment by sunoru** [comment]
@pthariensflame Hi, yes! I have been too busy myself recently but it would be great if anyone could start working on it. Let's discuss in #20
